### ISSUE TITLE
设置端口不成功

### ISSUE THREAD

**Issue by moboard** [Xuanwo/qingchat#2]
->>> qingchat config port 7777                             
Traceback (most recent call last):
  File "/usr/bin/qingchat", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/qingchat/cli.py", line 247, in main
    config_port(arguments['<port>'])
  File "/usr/lib/python3.5/site-packages/qingchat/cli.py", line 99, in config_port
    print("您的服务器端端口被设置为： %d" % port)
TypeError: %d format: a number is required, not str

---------------
这个是不是和端口在使用有关？

**Comment by Xuanwo** [comment]
这个是软件这边的一个BUG，输出的时候写错了

**Comment by moboard** [comment]
收到。pip那边还没更新是吧。
